### ISSUE TITLE
Affichage d'une torche posée par un autre joueur

### ISSUE THREAD

**Issue by plugnplay0** [darkelfe/ColoredTorches#1]
Une torche rouge, posée par un autre joueur, apparaît blanche et sans flamme.
En essayant de la collecter, crash avec l'erreur :
`java.lang.IllegalArgumentException: Cannot set property PropertyColor{name=color, clazz=class java.lang.String, values=[white, orange, magenta, lightblue, yellow, lime, pink, gray, silver, cyan, purple, blue, brown, green, red, black]} to null on block coloredtorches:torch, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:235) ~[awu$a.class:?]
	at com.darkelfe14728.coloredtorches.torch.TorchBlock.func_176221_a(TorchBlock.java:189) ~[TorchBlock.class:?]
	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:191) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:230) ~[ForgeHooks.class:?]`

**Comment by darkelfe14728** [comment]
Normalement corrigée avec la version 1.0.1 => a tester

**Comment by darkelfe14728** [comment]
Problème toujours pas corrigé.

Il semblerais que quand un joueur pose une torche, le serveur / les autre clients ne reçoivent pas immédiatement le TileEntity associé, d'où une texture "fausse" .

**Comment by darkelfe14728** [comment]
Corrigé dans v1.0.2
